global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["127.0.0.1:8000"]

  - job_name: "pushgateway"
    static_configs:
      - targets: ["127.0.0.1:9091"]
